_prefs: 
  mapid: ryanjhodge.785af934
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -115.9994
  - 33.987
  - 16
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 11
name: jotr-vegmap
source: "mapbox:///ryanjhodge.vbowjvhy"
styles: 
  - style.mss
template: ''
