_prefs: 
  mapid: ryanjhodge.23f33aa8
  saveCenter: true
_properties: {}
attribution: National Park Service
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -116.1847
  - 33.9406
  - 14
description: Joshua Tree National Park Vegetation Map
format: "png8:m=h:c=32"
interactivity_layer: vegetation
layers: null
maxzoom: 16
minzoom: 11
name: Joshua Tree National Park Vegetation Map
source: "mapbox:///ryanjhodge.wnfgk3xr"
styles: 
  - style.mss
template: "<b>Class:</b> {{class}}<br /><b>Macrogroup:</b> {{macrogroup}}<br /><b>Association:</b> {{mapunit_name}}"
