_prefs: 
  mapid: ryanjhodge.785af934
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -116.1832
  - 33.9771
  - 12
description: ''
format: "png8:m=h"
interactivity_layer: vegetation
layers: null
maxzoom: 16
minzoom: 11
name: jotr-vegmap
source: "mapbox:///ryanjhodge.vbowjvhy"
styles: 
  - style.mss
template: "{{MapUnit_Na}}"
